#!/bin/bash

# Creates containers based on docker-compose.yml file
# Note that after service creation the load balancer name, container name and port are considered immutable
# for that service definition
# http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html#load-balancing-concepts


# Create Application Load Balancer for the service and container roles
terraform apply

# Load variables generated by terraform into the environment
. .pipelines/export_env_vars.sh

# Start the service referencing resources created in the terraform script
ecs-cli compose \
    --task-role-arn $ECS_TASK_ROLE \
    service up \
    --target-group-arn $ALB_TARGET_GROUP \
    --role $ALB_ROLE \
    --container-name $ECS_ENTRY_CONTAINER \
    --container-port $ECS_ENTRY_PORT \
    --cluster $ECS_CLUSTER
